awesome:
  - README.md
  - data/**/*

docs:
  - .github/**/*
  - AGENTS.md
  - ABOUT.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - CITATION.cff
  - LICENSE*
  - SECURITY.md
  - package.json
  - pnpm-lock.yaml
  - utils/**/*
  - .npmrc
  - .prettierrc
  - .prettierignore
  - .gitattributes
  - .gitignore
