exclude = [
  "http://computerarchiv-muenchen.de/",
  "http://www.sfa-laboratory.ch/sr/cubestest/index.php",
  "http://www.cosmov.uzh.ch/",
  "http://www.infoclio.ch/en/edition-projects",
  "https://anneepolitique.swiss/",
  "https://archive.org/",
  "https://cdm21048.contentdm.oclc.org/",
  "https://www.archivesportaleurope.net/",
  "https://chroniclingamerica.loc.gov/",
  "https://dlas.uncg.edu/",
  "https://dp.la/",
  "https://hls-dhs-dss.ch/",
  "https://legacy.lib.utexas.edu/maps/",
  "https://mapire.eu/",
  "https://www.mural.ch/",
  "https://sites.usnh.edu/hoslac/",
  "https://southasiacommons.net/",
  "https://sources-online.org/index.html",
  "https://anno.onb.ac.at/",
  "https://digitalcollections.universiteitleiden.nl/imagecollection-kitlv",
  "https://druckschriften-digital.marchivum.de/",
  "https://swisscollections.ch/",
  "https://ub.unibas.ch/de/historische-bestaende/wirtschaftsarchive/",
  "https://www.amtsdruckschriften.bar.admin.ch/",
  "https://www.archeco.info/",
  "https://www.davidrumsey.com/",
  "https://www.digitaltransgenderarchive.net/",
  "https://www.e-manuscripta.ch/",
  "https://www.e-newspaperarchives.ch/",
  # Confirmed online in a human browser on 2026-09-05; automated requests time out.
  '^https://www\.e-rara\.ch/?$',
  "https://www.adfontes.uzh.ch/",
  "https://www.cgwmuseum.org/",
  "https://www.europeana.eu/",
  "https://www.gnu.org/licenses/",
  "https://www.gnu.org/licenses/agpl-3.0.html",
  "https://www.hathitrust.org/",
  "https://www.lexm.uni-hamburg.de/content/index.xml",
  "https://www.monasterium.net/mom/home",
  "https://www.nationaalarchief.nl/",
  "https://www.oldbaileyonline.org/",
  "https://www.projekt-gutenberg.org/",
  "https://www.proquest.com/index",
  "https://www.wdl.org/",
  "http://www.memobase.ch/",
  "http://gams.uni-graz.at/context:vase",
  "http://www.publicbooks.org/public-books-database/"
]

timeout = 30
max_retries = 2
format = "compact"
no_progress = true
cache = true
max_cache_age = "1d"
cache_exclude_status = "400..=499"
accept = ["100..=103", "200..=299", "429", "503", "521", "522", "524"]
