name: awesome-lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: test with Node '12.x'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install --global awesome-lint
    - run: awesome-lint
