name: changelog

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Generate unreleased changelog
        run: |
          LAST_COMMIT=$(git log -n 1 --format=%H -- CHANGELOG.md)
          npx git-cliff --config cliff-unreleased.toml $LAST_COMMIT..HEAD > unreleased.md

      - name: Output changelog to summary
        run: |
          echo "## New Changelog Entries (Since last CHANGELOG.md edit)" >> $GITHUB_STEP_SUMMARY
          cat unreleased.md >> $GITHUB_STEP_SUMMARY
