name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: 'Hi there! Thanks for opening your first issue!'
          pr_message: 'Hi there! Thanks for opening your first pull request! Please make sure it references the issue where your proposal was discussed and accepted, as required by CONTRIBUTING.md.'
